export const PLACE_ORDER_SELECTED_ITEMS = "PLACE_ORDER_SELECTED_ITEMS";
export const CONSUME_MORE_ITEMS = "CONSUME_MORE_ITEMS";
export const PROCEED_TO_BILLING = "PROCEED_TO_BILLING";
export const LEAVE_AND_RESET = "LEAVE_AND_RESET";
export const LEAVE_AND_CHANGESCREEN = "LEAVE_AND_CHANGESCREEN";
export const PROCEED_TO_BILLING_RELOAD = " PROCEED_TO_BILLING_RELOAD";
export const CONSUME_ITEMS_RELOAD = " CONSUME_ITEMS_RELOAD";

export const CHANGE_SCREEN = "CHANGE_SCREEN";
